### ISSUE TITLE
Implement selector argument type for scores/advancements

### ISSUE THREAD

**Issue by Arcensoth** [Arcensoth/language-mcfunction#1]

**Comment by Arcensoth** [comment]
Added in v0.3.0

**Comment by FVbico** [comment]
Making it marked red makes it seem there’s something wrong, perhaps mark it blue?

**Comment by Arcensoth** [comment]
See #11 ; the red is not intended but should be an easy fix. We'll have to wait for the next release of linguist which will auto-update to the most recent release of language-mcfunction.
