### ISSUE TITLE
[Request] Add submission guidelines

### ISSUE THREAD

**Issue by TheMrZZ** [Arcensoth/language-mcfunction#15]
Having submission guidelines would help people wanting to contribute (like me).

It could recap:
- What important files do, to have an idea of which files should be changed to add a functionality / fix a bug
- What commands are used to compile files (if needed) 
- Any additional tips from the main contributor (you) 

This project is very interesting, and I'd like to help with my free time. Having guidelines would help me a lot to contribute!

**Comment by Arcensoth** [comment]
Good idea, this would be helpful. For all contributors, including myself. I'll work on contribution guidelines alongside the handful of bugfixes when I get a solid block of time later this week(end).

**Comment by Arcensoth** [comment]
Added [CONTRIBUTING.md](https://github.com/Arcensoth/language-mcfunction/blob/master/CONTRIBUTING.md) in b3f9dde which outlines the repository structure and other useful information for contributors.

Let me know if you think of anything else that could be useful there.
