### ISSUE TITLE
Characters appearing at the end of some commands

### ISSUE THREAD

**Issue by Arcensoth** [Arcensoth/language-mcfunction#16]
![image](https://cdn.discordapp.com/attachments/154777837382008833/557670609962663976/Screenshot_20190319-220141.png)

**Comment by Arcensoth** [comment]
Cannot reproduce. Pinging @Misode for more info...

**Comment by misode** [comment]
The issue appears for me in some mcfunction files on the GitHub site.
[example file that doesn't reproduce this issue](https://github.com/Gamemode4Dev/GM4_Datapacks/blob/master/gm4_bat_grenades/data/bat_grenades/functions/main.mcfunction)
[example file that does reproduce the issue](https://github.com/Gamemode4Dev/GM4_Datapacks/blob/master/gm4_phantom_scarecrows/data/phantom_scarecrows/functions/main.mcfunction)

**Comment by Arcensoth** [comment]
At some point - probably as a side-effect of an earlier fix - I must have [fixed the trailing arguments being highlighted as errors](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2FArcensoth%2Flanguage-mcfunction%2Fblob%2Fmaster%2Fmcfunction.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2FGamemode4Dev%2FGM4_Datapacks%2Fblob%2Fmaster%2Fgm4_phantom_scarecrows%2Fdata%2Fphantom_scarecrows%2Ffunctions%2Fmain.mcfunction&code=), but the `^M` is a slightly different red and I don't think it's a problem with the syntax highlighter. Here's some research:

- https://github.com/atom/atom/issues/3105#issuecomment-304363782
- https://stackoverflow.com/questions/1822849/what-are-these-ms-that-keep-showing-up-in-my-files-in-emacs
-https://superuser.com/questions/1217622/how-can-i-remove-the-m-from-my-file-in-sublime-text-3

It looks like people might be committing files with CRLF and then GitHub decides to force-highlight the carriage returns.

We'll see how the next Linguist update handles the affected files and re-open if it's clear there's more to be done here.

**Comment by Arcensoth** [comment]
An update, for posterity:

GitHub Linguist has been updated, and is now running v0.13.0 of language-mcfunction.

As expected, the trailing arguments are being highlighted properly but the `^M` characters remain:

https://github.com/Gamemode4Dev/GM4_Datapacks/blob/master/gm4_phantom_scarecrows/data/phantom_scarecrows/functions/main.mcfunction#L2

Like I mentioned in my last comment, I'm not confident that this is a problem with the grammar itself but instead that people are committing carriage returns to mcfunction files. It may be the grammar's fault that these characters are being highlighted, but after some testing (via github-lightshow) I was unable to remove these characters by any means.

Until I have more definitive information about the problem and/or people reporting it, I'm going to work under the assumption that this is out of the grammar's control.

**Comment by Arcensoth** [comment]
Re-opening because this is still a problem and it's probably something that can be fixed with some effort.

**Comment by Arcensoth** [comment]
I should really create a new issue for this.

**Comment by Arcensoth** [comment]
(See #32 for a new report focused on the line-endings specifically.)
