### ISSUE TITLE
Show errors for quoted keys in entity selectors

### ISSUE THREAD

**Issue by SPGoding** [Arcensoth/language-mcfunction#28]
e.g. `say @e["tag"=foo]`

**Comment by Arcensoth** [comment]
@SPGoding Thanks, I'll look into it. I didn't even know this was valid. Is there any case where it's actually useful?

**Comment by SPGoding** [comment]
I don't think it's useful neither :p

So this may not be an important bug.

**Comment by Arcensoth** [comment]
I'll see how much further it will complicate the selector logic, but ideally since the game supports I would like to as well. I might dive in with this alongside #27 since both seem to be related in that they involve quoted keys of some kind.

**Comment by Arcensoth** [comment]
Fixed in a492683
