### ISSUE TITLE
Hex Colors marked as problem in tellraw command

### ISSUE THREAD

**Issue by Mahlarian** [Arcensoth/language-mcfunction#38]
I'm sure this is already known about and is going to be fixed in an update, but in case it isn't..

Tellraw now supports custom hex colors in its NBT. However, using it results in a problem although it's valid.
![image](https://user-images.githubusercontent.com/32558416/86835514-3bc42c80-c06a-11ea-940e-12b30bc9c8c8.png)

**Comment by Arcensoth** [comment]
@Mahlarian The language-mcfunction extension only provides highlighting, not the warning indicators and pop-ups. Are you using another datapack extension that would be causing this? Looks like DHP, which is likely to be updated by SPG in the near future.

**Comment by Mahlarian** [comment]
Well that's embarrassing, you were right, I got extensions mixed up. So sorry for getting that confused! Thanks for your help
