### ISSUE TITLE
spawnpoint command now supports rotation

### ISSUE THREAD

**Issue by xombiemike** [Arcensoth/language-mcfunction#39]
The spawnpoint command now supports rotation. Please update error validation. The following example is valid:
`spawnpoint @p -35 254 10 162.5`

**Comment by Arcensoth** [comment]
> The language-mcfunction extension only provides highlighting, not the warning indicators and pop-ups. Are you using another datapack extension that would be causing this? Looks like DHP, which is likely to be updated by SPG in the near future.

See also:
- https://github.com/Arcensoth/language-mcfunction/issues/37#issuecomment-653945671
- https://github.com/Arcensoth/language-mcfunction/issues/38#issuecomment-660613368

**Comment by Arcensoth** [comment]
(I also added #40 in light of all the recent misdirected bug reports.)
