### ISSUE TITLE
Commands Showing as Red

### ISSUE THREAD

**Issue by myxxmikeyxx** [Arcensoth/language-mcfunction#46]
**Is your feature request related to a problem? Please describe.**
When using any key words as effect, execute, and tellraw. It is all fine but the text after those are all bright red and underlined.

**Describe the solution you'd like**
The give, me, kill, summon, gamerule, setspawn, setworldspawn, and spawn commands are all bright red.
These being red make it seem like the command is not right. Another nice feature would be to just look for those key words and assume that the command following it is correct and not red as well.

setworldspawn.mcfunction: `setworldspawn`
setspawn.mcfunction: `spawnpoint @p ~ ~ ~`
home.mcfunction: `gamerule keepinventory true
execute at @s run kill @s
gamerule keepinventory false`
heal.mcfunction: `effect @p instant_health 10 10 true
effect @e instant_health 10 10 true
effect @p[r=1,c=1] saturation 10 10 true
effect @e[r=1,c=1] saturation 10 10 true`
dragon_summon.mcfunction: `summon ender_dragon`
dragon_kill.mcfunction: `kill @e[type=ender_dragon]`
diamond_tools.mcfunction: `give @s diamond_sword
give @s diamond_shovel
give @s diamond_pickaxe
give @s diamond_axe
me Has been given §bDiamond Tools§r.
tellraw @s{"rawtext":[{"text":"This is:\n/tellraw"}]}`

**Comment by myxxmikeyxx** [comment]
![Capture](https://user-images.githubusercontent.com/1766849/117173352-acc39600-ad9a-11eb-8197-80dfc480ffcb.PNG)

**Comment by Arcensoth** [comment]
@myxxmikeyxx Looks like you're using the experimental/WIP `mcfunction-snapshot` grammar instead of the default `mcfunction` one.

You can switch back to `mcfunction` in the bottom-right corner:

![image](https://user-images.githubusercontent.com/1885643/117195117-e6a09680-adb2-11eb-90a3-e5dbfce8b15a.png)

**Comment by myxxmikeyxx** [comment]
Yep that was it, I needed to change my settings file because it had `"files.associations": {
  "*.mcfunction": "mcfunction-snapshot"
}`
