### ISSUE TITLE
New Item command for 1.17

### ISSUE THREAD

**Issue by Speedoxx** [Arcensoth/language-mcfunction#48]
Can the new item command in version 1.17 be supported by the extension? Because right now it's constantly giving me errors... TY
Love the extension btw!

**Comment by SPGoding** [comment]
language-mcfunction does not give out errors on commands. You are probably using the Data-pack Helper Plus extension, which already provides support for 1.17 commands long ago. You just need to change `datapack.env.cmdVersion`, `datapack.env.dataVersion`, and `datapack.env.jsonVersion` for that extension to `1.17`.

**Comment by Arcensoth** [comment]
Thanks @SPGoding for pointing @Speedoxx in the right direction.

For future reference @Speedoxx please see #40
