### ISSUE TITLE
Implement single-quoted strings (as of 19w08a snapshot)

### ISSUE THREAD

**Issue by Solid-Block** [Arcensoth/language-mcfunction#8]
Single quote is supported now. For example:
`/give @s diamond_sword{display:{Name:'{"text":"abc"}'}}`

**Comment by Arcensoth** [comment]
I have this implemented in the version-specific grammar (unreleased, WIP) but haven't back-ported to the current version-agnostic (current, default) grammar yet. Should be a quick fix for a v0.7.0 release. Thanks for the reminder!

**Comment by Arcensoth** [comment]
Added in v0.7.0
